<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DPdmpKe' shared service.

return $this->privates['.service_locator.DPdmpKe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'data' => ['privates', '.errored..service_locator.DPdmpKe.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.DPdmpKe": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'validator' => ['privates', 'api_platform.validator', 'getApiPlatform_ValidatorService.php', true],
], [
    'data' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
    'em' => '?',
    'validator' => '?',
]);
