<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZW1lj7w' shared service.

return $this->privates['.service_locator.ZW1lj7w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categoryTranslationRepository' => ['privates', 'App\\Repository\\CategoryTranslationRepository', 'getCategoryTranslationRepositoryService.php', true],
], [
    'categoryTranslationRepository' => 'App\\Repository\\CategoryTranslationRepository',
]);
