<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rbvsq4D' shared service.

return $this->privates['.service_locator.rbvsq4D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'historyRepository' => ['privates', 'App\\Repository\\HistoryRepository', 'getHistoryRepositoryService.php', true],
], [
    'em' => '?',
    'historyRepository' => 'App\\Repository\\HistoryRepository',
]);
