<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\DownloadFileAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once \dirname(__DIR__, 4).'/src/Controller/DownloadFileAction.php';

$this->services['App\\Controller\\DownloadFileAction'] = $instance = new \App\Controller\DownloadFileAction();

$instance->setContainer(($this->privates['.service_locator.pNNo5z3'] ?? $this->load('get_ServiceLocator_PNNo5z3Service.php'))->withContext('App\\Controller\\DownloadFileAction', $this));

return $instance;
