<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.fixtures_load_command' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/CountryFixtures.php';
include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/DependentFixtureInterface.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/AddressFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/CompanyFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/TemplateFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/ClientFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/InvoiceFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/OrderFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/RoleFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/ProductFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/UserFixtures.php';
include_once \dirname(__DIR__, 4).'/src/DataFixtures/TextFixtures.php';

$a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($this);
$a->addFixtures([0 => ['fixture' => new \App\DataFixtures\CountryFixtures(), 'groups' => []], 1 => ['fixture' => new \App\DataFixtures\AddressFixtures(), 'groups' => []], 2 => ['fixture' => new \App\DataFixtures\CompanyFixtures(), 'groups' => []], 3 => ['fixture' => new \App\DataFixtures\TemplateFixtures(), 'groups' => []], 4 => ['fixture' => new \App\DataFixtures\ClientFixtures(), 'groups' => []], 5 => ['fixture' => new \App\DataFixtures\InvoiceFixtures(), 'groups' => []], 6 => ['fixture' => new \App\DataFixtures\OrderFixtures(), 'groups' => []], 7 => ['fixture' => new \App\DataFixtures\RoleFixtures(), 'groups' => []], 8 => ['fixture' => new \App\DataFixtures\ProductFixtures(), 'groups' => []], 9 => ['fixture' => new \App\DataFixtures\UserFixtures(($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php'))), 'groups' => []], 10 => ['fixture' => new \App\DataFixtures\TextFixtures(), 'groups' => []]]);

$this->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ($this->services['doctrine'] ?? $this->getDoctrineService()));

$instance->setName('doctrine:fixtures:load');

return $instance;
