<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\Command\ElasticaIndexSearchCommand' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/src/Command/ElasticaIndexSearchCommand.php';

return $this->services['console.command.public_alias.App\\Command\\ElasticaIndexSearchCommand'] = new \App\Command\ElasticaIndexSearchCommand(($this->privates['App\\Service\\Elastica\\Client\\ElasticaClientSearch'] ?? $this->load('getElasticaClientSearchService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
