<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\GoogleClient' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Service/GoogleClient.php';
include_once \dirname(__DIR__, 4).'/vendor/google/apiclient/src/Google/Client.php';

$a = new \Google_Client();
$a->setDeveloperKey($this->getEnv('GOOGLE_API_KEY'));
$a->setClientId($this->getEnv('GOOGLE_CLIENT_ID'));
$a->setClientSecret($this->getEnv('GOOGLE_CLIENT_SECRET'));

return $this->privates['App\\Service\\GoogleClient'] = new \App\Service\GoogleClient($a, ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
