<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\Command\GoogleAuthCommand' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/src/Command/GoogleAuthCommand.php';

return $this->services['console.command.public_alias.App\\Command\\GoogleAuthCommand'] = new \App\Command\GoogleAuthCommand(($this->privates['App\\Repository\\UserRepository'] ?? $this->load('getUserRepositoryService.php')), ($this->privates['App\\Service\\GoogleClient'] ?? $this->load('getGoogleClientService.php')));
