<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'gesdinet.jwtrefreshtoken.send_token' shared service.

include_once \dirname(__DIR__, 4).'/vendor/gesdinet/jwt-refresh-token-bundle/EventListener/AttachRefreshTokenOnSuccessListener.php';

return $this->privates['gesdinet.jwtrefreshtoken.send_token'] = new \Gesdinet\JWTRefreshTokenBundle\EventListener\AttachRefreshTokenOnSuccessListener(($this->services['gesdinet.jwtrefreshtoken.refresh_token_manager'] ?? $this->load('getGesdinet_Jwtrefreshtoken_RefreshTokenManagerService.php')), 28800, ($this->services['validator'] ?? $this->getValidatorService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), 'username', 'refresh_token', false);
