<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'liip_imagine.binary.mime_type_guesser' shared service.

include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Binary/MimeTypeGuesserInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Binary/SimpleMimeTypeGuesser.php';

return $this->privates['liip_imagine.binary.mime_type_guesser'] = new \Liip\ImagineBundle\Binary\SimpleMimeTypeGuesser(\Symfony\Component\Mime\MimeTypes::getDefault());
