<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\DataProvider\ProductCollectionDataProvider' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
include_once \dirname(__DIR__, 4).'/src/Service/DataProvider/ProductCollectionDataProvider.php';

return $this->privates['App\\Service\\DataProvider\\ProductCollectionDataProvider'] = new \App\Service\DataProvider\ProductCollectionDataProvider(($this->privates['App\\Service\\Elastica\\Client\\ElasticaClientProduct'] ?? $this->load('getElasticaClientProductService.php')), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
