<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Gesdinet\JWTRefreshTokenBundle\Command\RevokeRefreshTokenCommand' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/vendor/gesdinet/jwt-refresh-token-bundle/Command/RevokeRefreshTokenCommand.php';

$this->privates['Gesdinet\\JWTRefreshTokenBundle\\Command\\RevokeRefreshTokenCommand'] = $instance = new \Gesdinet\JWTRefreshTokenBundle\Command\RevokeRefreshTokenCommand(($this->services['gesdinet.jwtrefreshtoken.refresh_token_manager'] ?? $this->load('getGesdinet_Jwtrefreshtoken_RefreshTokenManagerService.php')));

$instance->setName('gesdinet:jwt:revoke');

return $instance;
