<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\TaskDeadlineAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/TaskDeadlineAction.php';

return $this->services['App\\Controller\\TaskDeadlineAction'] = new \App\Controller\TaskDeadlineAction(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
