<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Division extends \App\Entity\Division implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'companies', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'bankName', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'bankAccountNumber', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'isVat', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'vatComment', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'addresses', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'documents', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'contacts', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'contactPerson', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'description', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'isActive'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'companies', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'bankName', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'bankAccountNumber', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'isVat', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'vatComment', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'addresses', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'documents', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'contacts', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'contactPerson', '' . "\0" . 'App\\Entity\\Division' . "\0" . 'description', 'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'isActive'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Division $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getSearchText(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSearchText', []);

        return parent::getSearchText();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsVat(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsVat', []);

        return parent::getIsVat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsVat(?bool $isVat): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsVat', [$isVat]);

        return parent::setIsVat($isVat);
    }

    /**
     * {@inheritDoc}
     */
    public function getVatComment(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVatComment', []);

        return parent::getVatComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setVatComment(?string $vatComment): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVatComment', [$vatComment]);

        return parent::setVatComment($vatComment);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddresses(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddresses', []);

        return parent::getAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function addAddress(\App\Entity\Address $address): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAddress', [$address]);

        return parent::addAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAddress(\App\Entity\Address $address): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAddress', [$address]);

        return parent::removeAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocuments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', []);

        return parent::getDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocument(\App\Entity\Document $document): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocument', [$document]);

        return parent::addDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocument(\App\Entity\Document $document): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocument', [$document]);

        return parent::removeDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacts', []);

        return parent::getContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function addContact(\App\Entity\Contact $contact): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContact', [$contact]);

        return parent::addContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContact(\App\Entity\Contact $contact): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContact', [$contact]);

        return parent::removeContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description = NULL): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactPerson(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactPerson', []);

        return parent::getContactPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactPerson(?string $contactPerson): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactPerson', [$contactPerson]);

        return parent::setContactPerson($contactPerson);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankName', []);

        return parent::getBankName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankName(?string $bankName): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankName', [$bankName]);

        return parent::setBankName($bankName);
    }

    /**
     * {@inheritDoc}
     */
    public function getBankAccountNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBankAccountNumber', []);

        return parent::getBankAccountNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBankAccountNumber(?string $bankAccountNumber): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBankAccountNumber', [$bankAccountNumber]);

        return parent::setBankAccountNumber($bankAccountNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanies(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanies', []);

        return parent::getCompanies();
    }

    /**
     * {@inheritDoc}
     */
    public function addCompany(\App\Entity\Company $company): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCompany', [$company]);

        return parent::addCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole(\App\Entity\Company $company): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', [$company]);

        return parent::removeRole($company);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($updatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updatedBy]);

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive(bool $isActive): \App\Entity\Division
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

}
