<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8ww7YMj' shared service.

return $this->privates['.service_locator.8ww7YMj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'file' => ['privates', '.errored..service_locator.8ww7YMj.App\\Entity\\File', NULL, 'Cannot autowire service ".service_locator.8ww7YMj": it references class "App\\Entity\\File" but no such service exists.'],
], [
    'file' => 'App\\Entity\\File',
]);
