<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..k1eVmS' shared service.

return $this->privates['.service_locator..k1eVmS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'textRepository' => ['privates', 'App\\Repository\\TextRepository', 'getTextRepositoryService.php', true],
], [
    'textRepository' => 'App\\Repository\\TextRepository',
]);
