<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api.event.authentication_success_listener' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/EventListener/AuthenticationSuccessListener.php';

return $this->privates['api.event.authentication_success_listener'] = new \App\EventListener\AuthenticationSuccessListener(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
