<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\CreateImageAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/CreateImageAction.php';

return $this->services['App\\Controller\\CreateImageAction'] = new \App\Controller\CreateImageAction(($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['validator'] ?? $this->getValidatorService()), $this);
