<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Category\CategoryFrontendGetItemAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/Category/CategoryFrontendGetItemAction.php';

return $this->services['App\\Controller\\Category\\CategoryFrontendGetItemAction'] = new \App\Controller\Category\CategoryFrontendGetItemAction();
