<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\Elastica\Client\ElasticaClientProduct' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Service/Elastica/Client/ElasticaClientBase.php';
include_once \dirname(__DIR__, 4).'/src/Service/Elastica/Client/ElasticaClientProduct.php';
include_once \dirname(__DIR__, 4).'/src/Service/Elastica/Client/ElasticaClient.php';

return $this->privates['App\\Service\\Elastica\\Client\\ElasticaClientProduct'] = new \App\Service\Elastica\Client\ElasticaClientProduct(($this->privates['App\\Service\\Elastica\\Client\\ElasticaClient'] ?? ($this->privates['App\\Service\\Elastica\\Client\\ElasticaClient'] = new \App\Service\Elastica\Client\ElasticaClient())), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['api_platform.iri_converter'] ?? $this->getApiPlatform_IriConverterService()));
