<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\Command\ElasticaIndexProductCommand' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
include_once \dirname(__DIR__, 4).'/src/Command/ElasticaIndexProductCommand.php';

return $this->services['console.command.public_alias.App\\Command\\ElasticaIndexProductCommand'] = new \App\Command\ElasticaIndexProductCommand(($this->privates['App\\Service\\Elastica\\Client\\ElasticaClientProduct'] ?? $this->load('getElasticaClientProductService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
