<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.8ww7YMj.App\Entity\File' shared service.

$this->throw('Cannot autowire service ".service_locator.8ww7YMj": it references class "App\\Entity\\File" but no such service exists.');
