<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\History\HistoryGetEntityCollectionAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/History/HistoryGetEntityCollectionAction.php';

return $this->services['App\\Controller\\History\\HistoryGetEntityCollectionAction'] = new \App\Controller\History\HistoryGetEntityCollectionAction();
