<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'liip_imagine.gd' shared service.

include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Factory/ClassFactoryAwareInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Image/ImagineInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Image/AbstractImagine.php';
include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Gd/Imagine.php';
include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Image/Metadata/MetadataReaderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Image/Metadata/AbstractMetadataReader.php';
include_once \dirname(__DIR__, 4).'/vendor/imagine/imagine/src/Image/Metadata/DefaultMetadataReader.php';

$this->privates['liip_imagine.gd'] = $instance = new \Imagine\Gd\Imagine();

$instance->setMetadataReader(new \Imagine\Image\Metadata\DefaultMetadataReader());

return $instance;
