<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Product\ProductFrontendGetItemAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/Product/ProductFrontendGetItemAction.php';

return $this->services['App\\Controller\\Product\\ProductFrontendGetItemAction'] = new \App\Controller\Product\ProductFrontendGetItemAction(($this->privates['App\\Service\\Elastica\\Client\\ElasticaClientProduct'] ?? $this->load('getElasticaClientProductService.php')));
