<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\SearchAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/SearchAction.php';

return $this->services['App\\Controller\\SearchAction'] = new \App\Controller\SearchAction();
