<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Text\TextFrontendGetItemAction' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Controller/Text/TextFrontendGetItemAction.php';

return $this->services['App\\Controller\\Text\\TextFrontendGetItemAction'] = new \App\Controller\Text\TextFrontendGetItemAction();
