<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOCQVqZ2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOCQVqZ2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOCQVqZ2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOCQVqZ2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOCQVqZ2\App_KernelDevDebugContainer([
    'container.build_hash' => 'OCQVqZ2',
    'container.build_id' => '20113896',
    'container.build_time' => 1601794068,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOCQVqZ2');
