<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLFKCeFV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLFKCeFV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLFKCeFV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLFKCeFV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLFKCeFV\App_KernelDevDebugContainer([
    'container.build_hash' => 'LFKCeFV',
    'container.build_id' => 'ae02410d',
    'container.build_time' => 1603120175,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLFKCeFV');
