vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        file:
            uri_prefix: /file
            upload_destination: asset_filesystem
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        image:
            uri_prefix: /image
            upload_destination: image_filesystem
            namer: Vich\UploaderBundle\Naming\UniqidNamer
