version: '3.2'

services:
  php:
    image: inshopgroup/docker-inshop-crm-api-php-fpm-dev:latest
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - .:/var/www:rw,cached
      - files-data:/var/www/var/files:rw
    networks:
      - api

  nginx:
    image: inshopgroup/docker-inshop-crm-api-nginx-prod:latest
    depends_on:
      - php
    volumes:
      - ./public:/var/www/public:ro
    ports:
      - ${PORT_API}:80
    networks:
      - api

  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - ${PORT_DATABASE}:5432
    networks:
      - api

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - ${PORT_ELASTIC}:9200
    networks:
      - api
      - esnet

  redis:
    image: redis:latest
    volumes:
      - redis-data:/var/lib/redis
    networks:
      - api

volumes:
  es-data: {}
  db-data: {}
  redis-data: {}
  files-data: {}
  images-data: {}

networks:
    esnet:
    api:
